# Site
repository: sproogen/resume-theme
#repository: pouriatabari.github.io 
favicon: images/favicon.ico

# Content configuration version
version: 2

# Personal info
name: Pouriya Mashali Tabari
title: DevOps Enginner
email: pouriya_tabari@outlook.com
website: pouriya-tabari.com

# Dark Mode (true/false/never)
darkmode: never

# Social links
#twitter_username: facespics
github_username:  pouriatabari
# stackoverflow_username: "00000001"
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
#instagram_username: jameswgrant
linkedin_username: pouria-mashali-tabari
# xing_username: jekyll
# pinterest_username: jekyll
#youtube_username: globalmtb
# googleplus_username: +jekyll
# orcid_username: 0000-0000-0000-0000

# Additional icon links

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Pouriya and I'm a Junior DevOps Engineer. As well as DevOps Engineer I also have experience making many services and solving problems. I have worked at a number of companies gaining teamwork and other skills.

content:
  - title: Experience # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Namava
        link: namava.ir
        # link_text: boringcompany.com
        sub_title: Junior DevOps Engineer
        caption: July 2022 - Present
        quote: >
          - automating tasks with <mark>Ansible</mark> and <mark>Shell-scripting</mark> ( sometimes with <mark>powershell</mark> )
          
          - OS troubleshooting ( <mark>Linux</mark> and <mark>Windows</mark> and other <mark>Unix</mark> systems )
          
          - Designing and implementing <mark>Kubernetes</mark> cluster on test environment
          
          - Upgrade and update many Services and Infrastructure
          
          - T-shoot by <mark>Grafana</mark> and <mark>zabbix</mark>
          
        #description: | # this will include new lines to allow paragraphs
        #    Every company needs its networks properly administered and The Boring Compay is no exception. Digging holes is hard and I play my part making sure the whole company stays connected. I lead a team of 5 people and enjoy driving the company to try new technologies.

        title: Shabake Gostar Kayer
        link: kayer.co.ir
        # link_text: boringcompany.com
        sub_title: Junior Linux administrator
        caption: March 2022 - June 2022
        quote: >
          - OS troubleshooting ( Linux )
          
          - Zabbix configuration
          
          - Database handling ( <mark>Mysql</mark> )
          
          - Running a lot of service on Swarm <mark>( Docker Cluster)</mark> 
          
          - Writing <mark>Shell-Script</mark> and Service file for zabbix configuration
          
          
  - title: Education # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: left
        title: Payam noor University
        caption: 2017 - 2023
        sub_title: BSc Computer Software Engineer
        #quote: >
          #Established in 1636, Harvard is the oldest higher education institution in the United States, and is widely regarded in terms of its influence, reputation, and academic pedigree as a leading university in not just the US but also the world.
        #description: | # this will include new lines to allow paragraphs
          #During my time at Harvard I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

          #I spent a lot of my free time as a committee member of the *Harvard Mountaineering Club* taking on roles such as *Trip Secretary* and *Vice-President*.

  - title: A Little More About Me
    layout: text
    content: | # this will include new lines to allow paragraphs
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:
      - Listening to musics
      - Watching movies and series
      - Skiing
      - Eating Pizza and traditional Iranian food

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
